### PR TITLE
add SSENSE and remove other sponsors 

### PR DESCRIPTION
**Pull request by laila-chammaa**
my stupid brain spelled the branch name wrong.. pls dont judge

https://user-images.githubusercontent.com/53190232/143788016-f8fe5f07-cd28-4666-89a3-1948e4dca1c7.mov

### CODE REVIEW

**Comment by dylanbobb** [comment]
I originally put the logo at the top of the card for Genetec to match the style of the existing sponsors, but now that we're more or less redoing everything, maybe it makes more sense to center them? Something like this maybe? 
image

Not really sure which looks better, but just an option :)

**Comment by laila-chammaa** [comment]
> I originally put the logo at the top of the card for Genetec to match the style of the existing sponsors, but now that we're more or less redoing everything, maybe it makes more sense to center them? Something like this maybe? image
> 
> Not really sure which looks better, but just an option :)

i tried it out, and it looks fine, but since sizing isn't consistent between the cards, it looks slightly off, not sure. i can push tho if u like it better

https://user-images.githubusercontent.com/53190232/143788848-dd21c28a-a1e7-467d-9f15-df3b9299a95d.mov

**Comment by dylanbobb** [comment]
> > I originally put the logo at the top of the card for Genetec to match the style of the existing sponsors, but now that we're more or less redoing everything, maybe it makes more sense to center them? Something like this maybe? image
> > Not really sure which looks better, but just an option :)
> 
> i tried it out, and it looks fine, but since sizing isn't consistent between the cards, it looks slightly off, not sure. i can push tho if u like it better
> 
>  Screen.Recording.2021-11-28.at.5.32.41.PM.mov

Ehh that's a good point, I only tried it out with 1 card so I didn't realize how janky it looked.
I think it's better how you have it now. 
Thanks for checking though :)

**Comment by laila-chammaa** [comment]
> > > I originally put the logo at the top of the card for Genetec to match the style of the existing sponsors, but now that we're more or less redoing everything, maybe it makes more sense to center them? Something like this maybe? image
> > > Not really sure which looks better, but just an option :)
> > 
> > 
> > i tried it out, and it looks fine, but since sizing isn't consistent between the cards, it looks slightly off, not sure. i can push tho if u like it better
> > Screen.Recording.2021-11-28.at.5.32.41.PM.mov
> 
> Ehh that's a good point, I only tried it out with 1 card so I didn't realize how janky it looked. I think it's better how you have it now. Thanks for checking though :)

no problemo~

**Comment by laila-chammaa** [comment]
@dylanbobb feel free to approve, doesn't seem like jose is free :// no rush tho, im good to wait

**Review by dylanbobb — APPROVED** [review]

**Comment by dylanbobb** [comment]
> @dylanbobb feel free to approve, doesn't seem like jose is free :// no rush tho, im good to wait

lol sorry, doesn't seem like I have the proper permissions, PR is still blocked with my approval.
We'll have to wait for Jose or someone else with perms

**Comment by laila-chammaa** [comment]
> > @dylanbobb feel free to approve, doesn't seem like jose is free :// no rush tho, im good to wait
> 
> lol sorry, doesn't seem like I have the proper permissions, PR is still blocked with my approval. We'll have to wait for Jose or someone else with perms

ahh lol, no worries then~ dankee

**Review by jsulba — APPROVED** [review]
code looks good

**Pull request merged**
